Repository Gaethering/Gaethering-Server, pull requests merged in 2022-12, with the labels that each got.

#10 회원 프로필 조회 controller 구현
  build.gradle
  src/main/java/com/gaethering/gaetheringserver/member/controller/MemberController.java
  src/test/java/com/gaethering/gaetheringserver/member/controller/MemberControllerTest.java
Labels: feature

#14 jwt 통한 회원 인증 및 인가 (RE)
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  build.gradle
  src/main/java/com/gaethering/gaetheringserver/config/RedisConfig.java
  src/main/java/com/gaethering/gaetheringserver/config/SecurityConfig.java
  src/main/java/com/gaethering/gaetheringserver/config/WebConfig.java
  src/main/java/com/gaethering/gaetheringserver/core/exception/GlobalExceptionHandler.java
  src/main/java/com/gaethering/gaetheringserver/filter/JwtAuthenticationFilter.java
  src/main/java/com/gaethering/gaetheringserver/member/controller/MemberController.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/LoginRequest.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/LoginResponse.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/LogoutRequest.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/ReissueTokenRequest.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/ReissueTokenResponse.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/AuthenticationFailException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/AuthorizationFailException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/DormantUserException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/InActiveUserException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/MemberAuthException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/TokenIncorrectException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/TokenInvalidException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/TokenNotExistException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/TokenNotExistUserInfoException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/controller/MemberAuthExceptionController.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/errorcode/MemberErrorCode.java
  src/main/java/com/gaethering/gaetheringserver/member/service/CustomUserDetailsService.java
  src/main/java/com/gaethering/gaetheringserver/member/service/MemberService.java
  src/main/java/com/gaethering/gaetheringserver/member/service/MemberServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/util/CustomAccessDeniedHandler.java
  src/main/java/com/gaethering/gaetheringserver/util/CustomAuthenticationEntryPoint.java
  src/main/java/com/gaethering/gaetheringserver/util/JwtProvider.java
  src/main/java/com/gaethering/gaetheringserver/util/RedisUtil.java
  src/test/java/com/gaethering/gaetheringserver/member/controller/MemberControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/controller/PetControllerTest.java
  src/test/resources/application-test.yml
Labels: feature

#11 회원 가입 기능 수정
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/main/java/com/gaethering/gaetheringserver/board/domain/Comment.java
  src/main/java/com/gaethering/gaetheringserver/core/exception/GlobalExceptionHandler.java
  src/main/java/com/gaethering/gaetheringserver/core/validator/EnumValid.java
  src/main/java/com/gaethering/gaetheringserver/core/validator/EnumValidator.java
  src/main/java/com/gaethering/gaetheringserver/core/validator/LocalDateValid.java
  src/main/java/com/gaethering/gaetheringserver/core/validator/LocalDateValidator.java
  src/main/java/com/gaethering/gaetheringserver/member/controller/MemberController.java
  src/main/java/com/gaethering/gaetheringserver/member/domain/Member.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/SignUpRequest.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/SignUpResponse.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/errorcode/MemberErrorCode.java
  src/main/java/com/gaethering/gaetheringserver/member/service/MemberService.java
  src/main/java/com/gaethering/gaetheringserver/member/service/MemberServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/pet/dto/PetProfileResponse.java
  src/main/java/com/gaethering/gaetheringserver/pet/service/PetService.java
  src/test/java/com/gaethering/gaetheringserver/member/controller/MemberControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/member/dto/SignUpRequestTest.java
  src/test/java/com/gaethering/gaetheringserver/member/service/MemberServiceTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/service/PetServiceImplTest.java
Labels: feature

#17 펫 추가 등록 기능 구현
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/main/java/com/gaethering/gaetheringserver/member/dto/SignUpRequest.java
  src/main/java/com/gaethering/gaetheringserver/pet/controller/PetController.java
  src/main/java/com/gaethering/gaetheringserver/pet/dto/PetRegisterRequest.java
  src/main/java/com/gaethering/gaetheringserver/pet/dto/PetRegisterResponse.java
  src/main/java/com/gaethering/gaetheringserver/pet/exception/ExceedRegistrablePetException.java
  src/main/java/com/gaethering/gaetheringserver/pet/exception/errorcode/PetErrorCode.java
  src/main/java/com/gaethering/gaetheringserver/pet/service/PetService.java
  src/main/java/com/gaethering/gaetheringserver/pet/service/PetServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/member/dto/SignUpRequestTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/controller/PetControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/dto/PetRegisterRequestTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/service/PetServiceTest.java
Labels: feature

#19 feat: 로그인 시 회원 정보 제공
  .github/badges/jacoco.svg
  src/main/java/com/gaethering/gaetheringserver/member/controller/MemberController.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/LoginInfoResponse.java
  src/main/java/com/gaethering/gaetheringserver/member/service/MemberService.java
  src/main/java/com/gaethering/gaetheringserver/member/service/MemberServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/pet/exception/RepresentativePetNotFoundException.java
  src/main/java/com/gaethering/gaetheringserver/pet/exception/errorcode/PetErrorCode.java
  src/test/java/com/gaethering/gaetheringserver/member/controller/MemberControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/member/service/MemberServiceTest.java
Labels: feature

#20 회원 팔로우 기능 및 Spring Rest Docs 추가
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/docs/asciidoc/follow.adoc
  src/docs/asciidoc/member.adoc
  src/docs/asciidoc/mypage.adoc
  src/main/java/com/gaethering/gaetheringserver/config/SecurityConfig.java
  src/main/java/com/gaethering/gaetheringserver/core/domain/BaseCreatedTimeEntity.java
  src/main/java/com/gaethering/gaetheringserver/core/exception/BusinessException.java
  src/main/java/com/gaethering/gaetheringserver/core/exception/ErrorCode.java
  src/main/java/com/gaethering/gaetheringserver/core/exception/GlobalExceptionHandler.java
  src/main/java/com/gaethering/gaetheringserver/member/controller/FollowController.java
  src/main/java/com/gaethering/gaetheringserver/member/controller/MemberController.java
  src/main/java/com/gaethering/gaetheringserver/member/domain/Follow.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/FollowResponse.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/ModifyMemberNicknameRequest.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/FollowException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/FollowNotFoundException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/MemberException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/auth/MemberAuthException.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/errorcode/FollowErrorCode.java
  src/main/java/com/gaethering/gaetheringserver/member/exception/errorcode/MemberErrorCode.java
  src/main/java/com/gaethering/gaetheringserver/member/repository/follow/FollowRepository.java
  src/main/java/com/gaethering/gaetheringserver/member/service/FollowService.java
  src/main/java/com/gaethering/gaetheringserver/member/service/FollowServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/pet/controller/PetController.java
  src/main/java/com/gaethering/gaetheringserver/pet/exception/PetException.java
  src/main/java/com/gaethering/gaetheringserver/pet/exception/errorcode/PetErrorCode.java
  src/main/resources/application.yml
  src/main/resources/static/docs/follow.html
  src/main/resources/static/docs/member.html
  src/main/resources/static/docs/mypage.html
  src/test/java/com/gaethering/gaetheringserver/member/controller/FollowControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/member/controller/MemberControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/member/repository/FollowRepositoryTest.java
  src/test/java/com/gaethering/gaetheringserver/member/service/FollowServiceTest.java
  src/test/java/com/gaethering/gaetheringserver/member/util/ApiDocumentUtils.java
Labels: feature

#21 Feat 7: 반려동물 프로필 수정, 삭제 구현
  src/main/java/com/gaethering/gaetheringserver/pet/controller/PetController.java
  src/main/java/com/gaethering/gaetheringserver/pet/domain/Pet.java
  src/main/java/com/gaethering/gaetheringserver/pet/dto/PetImageUpdateResponse.java
  src/main/java/com/gaethering/gaetheringserver/pet/dto/PetProfileResponse.java
  src/main/java/com/gaethering/gaetheringserver/pet/dto/PetProfileUpdateRequest.java
  src/main/java/com/gaethering/gaetheringserver/pet/exception/FailedDeletePetException.java
  src/main/java/com/gaethering/gaetheringserver/pet/exception/FailedDeleteRepresentativeException.java
  src/main/java/com/gaethering/gaetheringserver/pet/exception/errorcode/PetErrorCode.java
  src/main/java/com/gaethering/gaetheringserver/pet/service/PetService.java
  src/main/java/com/gaethering/gaetheringserver/pet/service/PetServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/member/repository/FollowRepositoryTest.java
  src/test/java/com/gaethering/gaetheringserver/member/repository/MemberRepositoryTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/controller/PetControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/dto/PetProfileUpdateRequestTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/service/PetServiceTest.java
Labels: feature

#24 Feat-15 게시물 작성 (RE)
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/main/java/com/gaethering/gaetheringserver/board/controller/PostController.java
  src/main/java/com/gaethering/gaetheringserver/board/domain/Category.java
  src/main/java/com/gaethering/gaetheringserver/board/domain/Comment.java
  src/main/java/com/gaethering/gaetheringserver/board/domain/Heart.java
  src/main/java/com/gaethering/gaetheringserver/board/domain/Post.java
  src/main/java/com/gaethering/gaetheringserver/board/domain/PostImage.java
  src/main/java/com/gaethering/gaetheringserver/board/dto/PostRequest.java
  src/main/java/com/gaethering/gaetheringserver/board/dto/PostResponse.java
  src/main/java/com/gaethering/gaetheringserver/board/exception/CategoryNotFoundException.java
  src/main/java/com/gaethering/gaetheringserver/board/exception/PostException.java
  src/main/java/com/gaethering/gaetheringserver/board/exception/errorCode/PostErrorCode.java
  src/main/java/com/gaethering/gaetheringserver/board/repository/CategoryRepository.java
  src/main/java/com/gaethering/gaetheringserver/board/repository/PostImageRepository.java
  src/main/java/com/gaethering/gaetheringserver/board/repository/PostRepository.java
  src/main/java/com/gaethering/gaetheringserver/board/service/PostService.java
  src/main/java/com/gaethering/gaetheringserver/board/service/PostServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/auth/LoginRequest.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/auth/LoginResponse.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/auth/LogoutRequest.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/auth/ReissueTokenRequest.java
  src/main/java/com/gaethering/gaetheringserver/member/dto/auth/ReissueTokenResponse.java
  src/test/java/com/gaethering/gaetheringserver/board/controller/PostControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/board/service/PostServiceTest.java
Labels: feature

#31 마이페이지 내가 쓴 글 조회
  .github/badges/jacoco.svg
  src/docs/asciidoc/mypage.adoc
  src/main/java/com/gaethering/gaetheringserver/domain/board/controller/CommentController.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/PostRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/controller/MemberController.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/dto/mypage/MyPostsResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/dto/mypage/PostInfo.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/service/member/MemberService.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/service/member/MemberServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/member/controller/MemberControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/member/service/MemberServiceTest.java
Labels: documentation, feature

#34 chat 관련 entity 추가
  src/main/java/com/gaethering/gaetheringserver/domain/chat/entity/ChatMessage.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/entity/ChatRoom.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/entity/ChatroomMember.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/entity/WalkingTime.java
Labels: feature

#36 담당 기능 Spring Rest Docs 추가
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/docs/asciidoc/member.adoc
  src/docs/asciidoc/pet.adoc
  src/main/java/com/gaethering/gaetheringserver/domain/member/dto/signup/SignUpRequest.java
  src/main/java/com/gaethering/gaetheringserver/domain/pet/dto/PetRegisterRequest.java
  src/test/java/com/gaethering/gaetheringserver/member/controller/MemberControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/member/dto/SignUpRequestTest.java
  src/test/java/com/gaethering/gaetheringserver/member/service/MemberServiceTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/controller/PetControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/dto/PetRegisterRequestTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/service/PetServiceTest.java
Labels: documentation, feature

#38 Feat 29: 게시글, 게시글 이미지 수정
  src/docs/asciidoc/board.adoc
  src/main/java/com/gaethering/gaetheringserver/domain/board/controller/PostController.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostImageUploadResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostUpdateRequest.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostUpdateResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/entity/Post.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/entity/PostImage.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/exception/NoPermissionUpdatePostException.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/exception/PostImageNotFoundException.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/exception/errorCode/PostErrorCode.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/HeartRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/PostService.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/controller/PostControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceTest.java
Labels: feature

#48 채팅방 만들기 기능
  .github/badges/jacoco.svg
  build.gradle
  src/docs/asciidoc/chat.adoc
  src/main/java/com/gaethering/gaetheringserver/domain/chat/controller/ChatController.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/dto/MakeChatRoomRequest.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/dto/WalkingTimeInfo.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/repository/WalkingTimeRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/service/ChatService.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/service/ChatServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/domain/chat/controller/ChatControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/domain/chat/service/ChatServiceTest.java
Labels: documentation, feature

#58 Feat 55 : 펫 프로필 Controller 테스트 코드 수정 및 Spring Rest Docs 추가
  src/docs/asciidoc/pet.adoc
  src/test/java/com/gaethering/gaetheringserver/pet/controller/PetControllerTest.java
Labels: documentation, feature

#63 Feat 59: 도메인별 디렉토리 분리
  src/main/java/com/gaethering/gaetheringserver/domain/aws/s3/S3Service.java
  src/main/java/com/gaethering/gaetheringserver/domain/aws/s3/S3ServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/service/member/MemberServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/pet/service/PetServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceTest.java
  src/test/java/com/gaethering/gaetheringserver/member/service/MemberServiceTest.java
  src/test/java/com/gaethering/gaetheringserver/member/service/S3ServiceTest.java
  src/test/java/com/gaethering/gaetheringserver/pet/service/PetServiceTest.java
Labels: feature

#62 Feat-54 게시물 댓글 조회
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/docs/asciidoc/comment.adoc
  src/main/java/com/gaethering/gaetheringserver/domain/board/controller/CommentController.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/CommentDetailResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/CommentsGetResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/CommentRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/CommentService.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/CommentServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/util/ScrollPagingUtil.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/controller/CommentControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/service/CommentServiceTest.java
Labels: documentation, feature

#72 Feat-57 카테고리별 게시물 목록 조회 및 게시물 상세 조회 (RE)
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/docs/asciidoc/board.adoc
  src/main/java/com/gaethering/gaetheringserver/domain/board/controller/PostController.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/HeartResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostDetailResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostGetImageUrlResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostGetOneResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostUpdateResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostWriteResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostsGetResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/entity/Comment.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/entity/Post.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/CustomPostRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/Impl/PostRepositoryImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/PostImageRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/PostRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/CommentServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/HeartServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/PostService.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/controller/HeartControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/controller/PostControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/service/CommentServiceTest.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/service/HeartServiceTest.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceTest.java
Labels: feature

#67 Feat 66 게시글 작성 로직 수정 및 쿼리 수정
  .github/badges/jacoco.svg
  src/main/java/com/gaethering/gaetheringserver/domain/board/controller/PostController.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostWriteRequest.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/CommentRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/CustomCommentRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/CustomHeartRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/HeartRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/impl/CommentRepositoryImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/impl/HeartRepositoryImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/PostService.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceTest.java
Labels: feature

#74 feat 73: 게시글 작성 response 수정
  .github/badges/jacoco.svg
  src/main/java/com/gaethering/gaetheringserver/domain/board/controller/PostController.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostWriteResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/controller/PostControllerTest.java
Labels: feature

#81 Feat-80 게시물 상세 조회 응답 변수 추가
  .github/badges/jacoco.svg
  src/docs/asciidoc/board.adoc
  src/main/java/com/gaethering/gaetheringserver/domain/board/dto/PostGetOneResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/controller/PostControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/domain/board/service/PostServiceTest.java
Labels: feature

#77 NGINX 설정 파일 작성
  nginx/nginx.conf
  nginx/sub/conf.d/no-ssl.default.conf
  nginx/sub/cross-origin/requests.conf
  nginx/sub/media_types/character_encoding.conf
  nginx/sub/media_types/mime_type.conf
  nginx/sub/security/content-security-policy.conf
  nginx/sub/security/cross-origin-policy.conf
  nginx/sub/security/permissions-policy.conf
  nginx/sub/security/server_software_information.conf
  nginx/sub/security/x-frame-options.conf
  nginx/sub/web_performance/cache_control.conf
  nginx/sub/web_performance/cache_expiration.conf
  src/main/java/com/gaethering/gaetheringserver/domain/board/repository/impl/PostRepositoryImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/repository/member/impl/MemberRepositoryImpl.java
Labels: feature, help wanted, invalid

#83 member profile info에 memberId 추가, room Info에 roomKey 추가
  src/docs/asciidoc/member.adoc
  src/main/java/com/gaethering/gaetheringserver/domain/chat/controller/ChatController.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/dto/MakeChatRoomResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/service/ChatService.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/dto/auth/LoginInfoResponse.java
  src/main/resources/static/docs/chat.html
  src/main/resources/static/docs/member.html
  src/test/java/com/gaethering/gaetheringserver/domain/chat/controller/ChatControllerTest.java
  src/test/java/com/gaethering/gaetheringserver/domain/chat/service/ChatServiceTest.java
  src/test/java/com/gaethering/gaetheringserver/member/controller/MemberControllerTest.java
Labels: documentation, hotfix

#79 Feat-78 jwt 인증 및 인가 실패 예외 처리 방법 수정
  .github/badges/jacoco.svg
  src/main/java/com/gaethering/gaetheringserver/domain/member/controller/MemberAuthExceptionController.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/exception/auth/AuthenticationFailException.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/exception/auth/AuthorizationFailException.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/jwt/auth/CustomAccessDeniedHandler.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/jwt/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/gaethering/gaetheringserver/domain/member/service/member/MemberServiceImpl.java
Labels: feature

#85 채팅방 목록 조회
  src/main/java/com/gaethering/gaetheringserver/domain/chat/controller/ChatController.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/dto/ChatRoomListInfo.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/dto/ChatRoomListResponse.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/repository/CustomChatRoomRepository.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/repository/impl/ChatRoomRepositoryImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/service/ChatService.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/service/ChatServiceImpl.java
Labels: documentation, feature

#89 채팅방 생성 시 멤버 추가, CORS 문제 해결
  .github/badges/jacoco.svg
  src/main/java/com/gaethering/gaetheringserver/config/SecurityConfig.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/service/ChatMessageServiceImpl.java
  src/main/java/com/gaethering/gaetheringserver/domain/chat/service/ChatServiceImpl.java
  src/test/java/com/gaethering/gaetheringserver/domain/chat/service/ChatServiceTest.java
Labels: bug, feature
